export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_FAIL="SIGNIN_FAIL";